# Generated by Django 6.0 on 2025-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='difficulty',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trek',
            name='height',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
